### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by 9mido** [danielmorell/se_bot_checker#6]
https://support.google.com/webmasters/answer/80553?hl=en#:~:text=To%20verify%20Googlebot%20as%20the,googlebot.com%20or%20google.com

https://blog.majsky.cz/detecting-google-bot-python-and-django/

https://github.com/macropin/django-googlebot

Does this package do something similar to the above links? Trying to understand a use case for this se_bot_checker package. Because I am not clear on what this package does.

**Comment by danielmorell** [comment]
Yes, this package does exactly what the first two links talk about. It allows you to verify the validity of a request that identifies as Googlebot or any other major search engine crawler.

However, that last link to _django-googlebot_ does something else. It adds a "googlebot" user and then logs Googlebot in under that user anytime it is crawling the site. This could be used to allow Google to index private content, without making it public to everyone.

This package is not restricted to Django. I use it in Django, but it can be used in a standalone manner as well.

If you do use this package with Django it would be wise to cache the results of the validation. The validation needs to make two network requests to verify a crawler's identity. If you do this for every request it will slow down your site's response time when Google is trying to index your site. Usually, caching the results for each IP for at least 24 hours is a good practice.

**Comment by 9mido** [comment]
Thanks for the quick reply back. 

If I understand you correctly, this package is similar to https://github.com/danmoz/django-fake-bot-detector also? It basically ensures that you are getting valid requests from legitimate crawlers. If you do not use a package like this, then your site might not be ranked correctly because there are fake bots trying to crawl your site besides the legitimate googlebot and other legit crawlers like social media ones? 

What is your recommended way of caching the results of the validation? Do you have an example of how to do that?

**Comment by danielmorell** [comment]
If you have malicious bots crawling your site it won't cause your site to "not be ranked correctly". Google does not care what you allow other bots to do on your website, just that you allow Googlebot to crawl your site. Before Google begins to rank your site, they have to index your site, and before they can index your site, they need to crawl your site. These are three different steps.

Implementing this does not require a cache backend in your Django project, but I highly recommend it you should read the [Django cache docs](https://docs.djangoproject.com/en/3.0/topics/cache/). I usually reach for [DiskCache](http://www.grantjenks.com/docs/diskcache/) or Redis for the cache backends.

I would recommend using some sort of prefixed string with the IP for the cache key. Something like `bot-ip-127-0-0-1`. What you store in the cache is up to you. You could store a simple `valid` or `invalid`, `True` / `False`, or some more information. It is up to you.

The validation would probably be a 5-step process.

1. Check the user agent string to see if it matches a bot you want to check.
1. If it is a bot user agent check if the request IP is already in the cache. If it is just return the result from the cache.
1. If the bot IP is not cached run the bot validation.
1. Cache the result of the validation.
1. Return the results of the validation.

If your Django is running behind a load balancer or proxy make sure you get the end user IP not the IP from your load balancer or proxy.

This is usually implemented as middleware. 

If your purpose is bot mitigation, you may want to not write this into your Django project. It would be better to perform this validation before the request ever made it to Django. It is more work, but you can implement it in Nginx or Apache, and it will save your Django instance from being bombarded with requests that you want to block anyway.

**Comment by 9mido** [comment]
So this app would be used to protect your site from being crawled by malicious bots who want to try and steal your content? 

How would you test this app to be sure that it worked? 

Thanks for the detailed description so far.

**Comment by danielmorell** [comment]
This package could be used for that, but it is more general purpose. 

Let's say you want to analyze your access log files to see if googlebot is actually crawling your content correctly. You would want to make sure to eliminate any fake googlebots from your logs before you analyze the data. You can use this package to do that.

This package is tested before each new release. As long as you are using it properly it will do what you ask it to. If you are using for bot mitigation, log files will be your best friend. However, you may want to create a test bot definition, that will successfully respond to the forward and reverse DNS lookups. You can find an example in the `tests` directory. Here is one for a custom bot definition that uses a local DNS lookup.

```python
class TestBot(TestCase):
    def setUp(self):
        self.bot = Bot.bot('dooglebot', 'dooglebot', ['.dooglebot.test'])
        self.bot('127.0.0.1', 'Mozilla/5.0 (compatible; Dooglebot/0.1; +http://www.dooglebot.test/bot.html)')
        self.host = self.bot.reverse_dns()
        self.valid = (True, 'dooglebot')
        self.invalid = (False, 'unknown')


    def test_run(self):
        self.assertTupleEqual(self.bot.run(), self.valid)


    def test_valid_user_agent(self):
        self.assertTrue(self.bot.valid_user_agent())


    def test_valid_domain(self):
        self.assertTrue(self.bot.valid_domain(self.host))


    def test_valid_ip(self):
        self.assertTrue(self.bot.valid_ip())


    def test_reverse_dns(self):
        self.assertTrue(self.host.endswith('.dooglebot.test'))


    def test_forward_dns(self):
        self.assertTrue(self.bot.forward_dns(self.host))


    def test_not_dooglebot_ip(self):
        try:
            is_dooglebot, name = self.bot(
                '0.0.0.0',
                'Mozilla/5.0 (compatible; Dooglebot/0.1; +http://www.dooglebot.test/bot.html)'
            )
        except DNSError:
            is_dooglebot, name = (False, 'unknown')
        self.assertTupleEqual((is_dooglebot, name), self.invalid)


    def test_not_dooglebot_user_agent(self):
        try:
            is_dooglebot, name = self.bot(
                '66.249.66.1',
                'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                '(KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36'
            )
        except DNSError:
            is_dooglebot, name = (False, 'unknown')
        self.assertTupleEqual((is_dooglebot, name), self.invalid)
```

You will need to set up a local DNS record in your `hosts` file for `www.dooglebot.test` or this test won't work. You can modify this to test your specific implementation needs.

**Comment by 9mido** [comment]
@danielmorell Thanks for the details. Another question. If I use something like this:

https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker

https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker

Is it even necessary to use this library?

**Comment by danielmorell** [comment]
Again the purpose for this package and projects like ultimate bad bot blocker are different. My package is designed to verify the authenticity of a search engine bot. Ultimate bad bot blocker is designed to stop malicious bots from accessing your website.
