### ISSUE TITLE
Change license?

### ISSUE THREAD

**Issue by pb-jeff-oneill** [danielmorell/se_bot_checker#7]
Hi Daniel, very cool project!  Would you consider changing the license to MIT or BSD?  GPLv3 is a very restrictive license, and this tool would get much wider adoption with a more permissive license.  I hope you will consider this request.

**Comment by danielmorell** [comment]
Thanks for pointing this out. I License almost everything MIT these days. However, a few years ago before I understood the implications, I defaulted to GPLv3.

I have updated the license to MIT. I will try to push a new release to PyPI sometime tomorrow with the new license.

**Comment by pb-jeff-oneill** [comment]
Thanks Daniel!
